local_backend: true
backend:
  name: git-gateway
media_folder: "/public/content/"
public_folder: '/content/'
collections:
- name: blog
  label: "Blog"
  folder: src/content/blog
  preview_path: blog/{{slug}}
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Description", name: "description", widget: "string"}
    - {label: "Publish Date", name: "publishDate", widget: "datetime"}
    - {label: "Authors", name: "authors", widget: "list"}
    - {label: "Draft", name: "isDraft", widget: "boolean", default: true}
    - {label: "Body", name: "body", widget: "markdown"}

previewStyles: 'src/styles/tailwind.css'